In [1]:
import pyREX
import pyREX.misc as misc
import MDAnalysis as mda
import numpy as np
from numpy.testing import assert_allclose


pre = "./files/1l2y/"
pdb = pre + "1l2y_ref.pdb"
tpr = pre + "traj.tpr"
xtc = pre + "traj.xtc"

mobile = mda.Universe(tpr, xtc, tpr_resid_from_one=True)
ref = mda.Universe(pdb)


import pyREX.analysis.analysis as ana

In [2]:
help(ana.shortest_RES_distances)

Help on function shortest_RES_distances in module pyREX.analysis.analysis:

shortest_RES_distances(u)
    Calculates shortest RES distances (all atom level) of universe u.
    Attention: Displayed RES ids always start with 1
    
    Args:
        u (str): structure path
        u (MDA universe/atomgrp): structure
    
    Returns:
        SD (np.arrray): NxN Matrix with shortest RES distances
                        i.e.: SD[0][0] is shortest distance RES0-RES0
                              SD[0][1] is shortest distance RES0-RES1
                              SD[0][2] is shortest distance RES0-RES2
                              etc.
        SD_d (np.array, dtype=object): detailed List with:
            [d_min, (RES_pair), (ATM_pair), (ATM_names)]



In [4]:
X = ana.shortest_RES_distances(ref)

In [5]:
np.save("files/1l2y/shortest_RES_distances.npy", X)

/home/arthur/.local/lib/python3.8/site-packages/numpy/core/_asarray.py:171: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order, subok=True)


In [6]:
Y = np.load("files/1l2y/shortest_RES_distances.npy", allow_pickle=True)

In [10]:
Y[1]

array([[1.3389152990798758, (1, 2), (15, 17), ('C', 'N')],
       [3.166102526712592, (1, 3), (15, 37), ('C', 'H')],
       [2.300860104882621, (1, 4), (16, 58), ('O', 'H')],
       [2.028726645660892, (1, 5), (16, 77), ('O', 'H')],
       [4.33433225870964, (1, 6), (16, 94), ('O', 'H')],
       [5.929565755446225, (1, 7), (16, 118), ('O', 'H')],
       [6.653776693500622, (1, 8), (16, 145), ('O', 'HG2')],
       [8.593230813191104, (1, 9), (16, 159), ('O', 'H')],
       [10.658579203630307, (1, 10), (16, 171), ('O', 'H')],
       [10.501038025760927, (1, 11), (16, 181), ('O', 'HA2')],
       [12.91245536170829, (1, 12), (16, 187), ('O', 'HD2')],
       [14.96004632667137, (1, 13), (16, 199), ('O', 'H')],
       [12.528950106860245, (1, 14), (16, 217), ('O', 'HG')],
       [16.031430506128704, (1, 15), (16, 225), ('O', 'C')],
       [10.429625368133811, (1, 16), (16, 239), ('O', 'HD2')],
       [11.353686480358164, (1, 17), (16, 264), ('O', 'O')],
       [9.98403329481919, (1, 18), (16

In [23]:
Y[1] == X[1]

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
 

In [22]:
Y[1,]

array([[1.3389152990798758, (1, 2), (15, 17), ('C', 'N')],
       [3.166102526712592, (1, 3), (15, 37), ('C', 'H')],
       [2.300860104882621, (1, 4), (16, 58), ('O', 'H')],
       [2.028726645660892, (1, 5), (16, 77), ('O', 'H')],
       [4.33433225870964, (1, 6), (16, 94), ('O', 'H')],
       [5.929565755446225, (1, 7), (16, 118), ('O', 'H')],
       [6.653776693500622, (1, 8), (16, 145), ('O', 'HG2')],
       [8.593230813191104, (1, 9), (16, 159), ('O', 'H')],
       [10.658579203630307, (1, 10), (16, 171), ('O', 'H')],
       [10.501038025760927, (1, 11), (16, 181), ('O', 'HA2')],
       [12.91245536170829, (1, 12), (16, 187), ('O', 'HD2')],
       [14.96004632667137, (1, 13), (16, 199), ('O', 'H')],
       [12.528950106860245, (1, 14), (16, 217), ('O', 'HG')],
       [16.031430506128704, (1, 15), (16, 225), ('O', 'C')],
       [10.429625368133811, (1, 16), (16, 239), ('O', 'HD2')],
       [11.353686480358164, (1, 17), (16, 264), ('O', 'O')],
       [9.98403329481919, (1, 18), (16

In [24]:
assert_allclose(Y[1], X[1])

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [30]:
Y[1:,][0]

array([[1.3389152990798758, (1, 2), (15, 17), ('C', 'N')],
       [3.166102526712592, (1, 3), (15, 37), ('C', 'H')],
       [2.300860104882621, (1, 4), (16, 58), ('O', 'H')],
       [2.028726645660892, (1, 5), (16, 77), ('O', 'H')],
       [4.33433225870964, (1, 6), (16, 94), ('O', 'H')],
       [5.929565755446225, (1, 7), (16, 118), ('O', 'H')],
       [6.653776693500622, (1, 8), (16, 145), ('O', 'HG2')],
       [8.593230813191104, (1, 9), (16, 159), ('O', 'H')],
       [10.658579203630307, (1, 10), (16, 171), ('O', 'H')],
       [10.501038025760927, (1, 11), (16, 181), ('O', 'HA2')],
       [12.91245536170829, (1, 12), (16, 187), ('O', 'HD2')],
       [14.96004632667137, (1, 13), (16, 199), ('O', 'H')],
       [12.528950106860245, (1, 14), (16, 217), ('O', 'HG')],
       [16.031430506128704, (1, 15), (16, 225), ('O', 'C')],
       [10.429625368133811, (1, 16), (16, 239), ('O', 'HD2')],
       [11.353686480358164, (1, 17), (16, 264), ('O', 'O')],
       [9.98403329481919, (1, 18), (16